branch-defaults:
  master:
    environment: bequest-production
environment-defaults:
  production:
    branch: null
    repository: null
global:
  application_name: bequest
  default_ec2_keyname: aws-eb
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Puma with Ruby 2.3
    running on 64bit Amazon Linux/2.4.3
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
